version: '2'
services:
  celery:
    build: .
    command: celery worker -l info --app=celery_setup
    volumes:
      - '.:/src'
  flower:
    build: .
    command: celery --app=celery_setup flower --port=5555
    volumes:
      - '.:/src'
    ports:
      - "5555:5555"
  redis:
    image: 'redis:3.0-alpine'
    command: redis-server --requirepass devpassword
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'
  db:
    restart: always
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
        POSTGRES_PASSWORD: secret
        POSTGRES_USER: flask
        POSTGRES_DB: flask_db
    ports:
      - "54325:5432"
  web:
    build: .
    restart: always
    command: bash ./deploy/start.sh
    environment: 
      - FLASK_ENV=development
    volumes:
      - .:/src
    ports:
      - "8005:8000"
    depends_on:
      - db
  nginx:
    restart: always
    build: ./nginx/.
    ports:
        - "80:80"
    volumes:
        - /www/static
    volumes_from:
        - web
    links:
        - web:web
volumes:
  postgres-data:
    driver: local
  redis:
    driver: local
