version: '2'
services:
  celery:
    build: .
    command: bash ./deploy/start-celery.sh
    volumes:
      - '.:/src'
  flower:
    build: .
    command: bash ./deploy/start-flower.sh
    volumes:
      - '.:/src'
    ports:
      - "5555:5555"
  redis:
    image: 'redis:3.0-alpine'
    command: redis-server --requirepass devpassword
    ports:
      - '6379:6379'
  db:
    restart: always
    image: postgres
    environment:
        POSTGRES_PASSWORD: secret
        POSTGRES_USER: flask
        POSTGRES_DB: flask_db
    ports:
      - "54325:5432"
  web:
    build: .
    restart: always
    command: bash ./deploy/start.sh
    environment: 
      - FLASK_ENV=development
    volumes:
      - .:/src
    ports:
      - "8005:8000"
    depends_on:
      - db
  nginx:
    restart: always
    build: ./nginx/.
    ports:
        - "80:80"
    volumes:
        - /www/static
    volumes_from:
        - web
    links:
        - web:web