"""empty message

Revision ID: d475c569a6f3
Revises: 517a05824aae
Create Date: 2017-04-05 04:03:04.020340

"""

# revision identifiers, used by Alembic.
revision = 'd475c569a6f3'
down_revision = '517a05824aae'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todoes')
    ### end Alembic commands ###
